import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
public class admin_change_password extends javax.swing.JFrame {

    /**
     * Creates new form admin_change_password
     */
    public admin_change_password() {
        initComponents();
        getContentPane().setBackground(Color.black);
        setTitle("Change Password");
        setSize(500,330);
        setVisible(true);
        ansfield1.setText(global.admin_name);
        ansfield1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field1 = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        field2 = new javax.swing.JLabel();
        field3 = new javax.swing.JLabel();
        ansfield1 = new javax.swing.JTextField();
        ansfield2 = new javax.swing.JPasswordField();
        afield3 = new javax.swing.JPasswordField();
        field4 = new javax.swing.JLabel();
        afield4 = new javax.swing.JPasswordField();
        changebt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        field1.setForeground(new java.awt.Color(255, 255, 255));
        field1.setText("Username");
        getContentPane().add(field1);
        field1.setBounds(69, 76, 93, 19);

        heading.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Change Password");
        getContentPane().add(heading);
        heading.setBounds(131, 17, 239, 28);

        field2.setForeground(new java.awt.Color(255, 255, 255));
        field2.setText("Old Password");
        getContentPane().add(field2);
        field2.setBounds(69, 116, 124, 16);

        field3.setForeground(new java.awt.Color(255, 255, 255));
        field3.setText("New Password");
        getContentPane().add(field3);
        field3.setBounds(69, 156, 124, 16);
        getContentPane().add(ansfield1);
        ansfield1.setBounds(310, 70, 117, 22);

        ansfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansfield2ActionPerformed(evt);
            }
        });
        getContentPane().add(ansfield2);
        ansfield2.setBounds(310, 110, 117, 22);

        afield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afield3ActionPerformed(evt);
            }
        });
        getContentPane().add(afield3);
        afield3.setBounds(310, 150, 117, 22);

        field4.setForeground(new java.awt.Color(255, 255, 255));
        field4.setText("Confirm New Password");
        getContentPane().add(field4);
        field4.setBounds(69, 193, 150, 16);

        afield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afield4ActionPerformed(evt);
            }
        });
        getContentPane().add(afield4);
        afield4.setBounds(310, 190, 117, 22);

        changebt.setText("Change Password");
        changebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtActionPerformed(evt);
            }
        });
        getContentPane().add(changebt);
        changebt.setBounds(138, 246, 151, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ansfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansfield2ActionPerformed

    private void afield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afield3ActionPerformed

    private void afield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afield4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afield4ActionPerformed

    private void changebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtActionPerformed
        String username=ansfield1.getText();
        String oldpassword=ansfield2.getText();
        String newpassword=afield3.getText();
        String connewpassword=afield4.getText();
        
       
        
        try{
            ResultSet rs=DBLoader.exexuteSQL("Select *from admin where username='"+username+"'");
            if(rs.next()){
                String dbpass=rs.getString("password");
                if(oldpassword.equals(dbpass)){
                    if(newpassword.equals(connewpassword)){
                        rs.updateString("password", newpassword);
                        rs.updateRow();
                        JOptionPane.showMessageDialog(this,"Updated");
                        dispose();
                        admin_login obj=new admin_login();
                    }else{
                        JOptionPane.showMessageDialog(this,"New Password and Confirm New Password must be same");
                    }
                }else{
                    JOptionPane.showMessageDialog(this,"Wrong Password(old)");
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_changebtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_change_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField afield3;
    private javax.swing.JPasswordField afield4;
    private javax.swing.JTextField ansfield1;
    private javax.swing.JPasswordField ansfield2;
    private javax.swing.JButton changebt;
    private javax.swing.JLabel field1;
    private javax.swing.JLabel field2;
    private javax.swing.JLabel field3;
    private javax.swing.JLabel field4;
    private javax.swing.JLabel heading;
    // End of variables declaration//GEN-END:variables
}
